_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 12
                - 45
                - 55
            "2":
                - 1
                - 12
                - 45
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batch_size:
    value: 200
group_name:
    value: qubits_8_layers_6_reps_8_samples_600
learning_rate:
    value: 0.005
loss_fn:
    value: cross_entropy
max_layers:
    value: 6
n_epochs:
    value: 500
n_layers:
    value: 6
n_qubits:
    value: 8
n_repeats:
    value: 10
n_reps:
    value: 8
optimizer:
    value: adam
project_name:
    value: Classification_mnist
save_best_model:
    value: true
save_epoch_metrics:
    value: true
seed:
    value: 2
test_every_epoch:
    value: true
use_wandb:
    value: true
